### ISSUE TITLE
How to train.

### ISSUE THREAD

**Issue by iminfine** [suhwan-cho/CRVOS#1]
I read your paper, thanks for your great work!
Could you please write an instruction about how to train CRVOS?

**Comment by suhwan-cho** [comment]
Thanks for your attention to our work!

You can find the training strategy at Section 2.4.
The implementation details can be found at Section 2.5.

If you need more help, please feel free to ask :)

**Comment by iminfine** [comment]
> Thanks for your attention to our work!
> 
> You can find the training strategy at Section 2.4.
> The implementation details can be found at Section 2.5.
> 
> If you need more help, please feel free to ask :)

Thanks, I will write my own training script, wish I can reproduce the pretrained CRVOS model.
It would be better if the official CRVOS code has a training script.

**Comment by iminfine** [comment]
Sorry, I can't reproduce the results. I retrained the model and tested on DAVIS16, the J &F score is 78.3%. 
Could you please share your training code?

**Comment by suhwan-cho** [comment]
> Sorry, I can't reproduce the results. I retrained the model and tested on DAVIS16, the J &F score is 78.3%.
> Could you please share your training code?

I'm sorry that we're not planning to share our training code now. 
However, it may be shared in the future after the paper is accepted.

**Comment by iminfine** [comment]
OK,I am looking forward.
