### ISSUE TITLE
Multi-clues.

### ISSUE THREAD

**Issue by gbaizj824** [suhwan-cho/CRVOS#3]
Do you train the model with multi-clues i.e. multi masks of the previous adjacent frames?
If yes, how about the performance?

**Comment by suhwan-cho** [comment]
Hi.
CRVOS is only trained with single-target scenarios.
Training the model with multiple targets at once is a challenging problem.

**Comment by gbaizj824** [comment]
> Hi.
> CRVOS is only trained with single-target scenarios.
> Training the model with multiple targets at once is a challenging problem.

Sorry, I didn't make it clear. I meant training CRVOS with single-target and use multi previous masks as clues.

**Comment by suhwan-cho** [comment]
Oh, I understand now.
Unlike the features, the masks are not consistent values.
Therefore, long-term masks are not used in most cases since they are not reliable.
